name: 'adventureworks_dbt'
version: '1.0.0'
config-version: 2

profile: 'adventureworks'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  table_name: []

models:
  adventureworks:
    staging:
      +schema: staging
    +on_schema_change: "sync_all_columns"
    +materialized: table
    +persist_docs:
      relation: true
      columns: true

    staging:
      +materialized: table
      +schema: staging
      +tags:
        - staging

    intermediate:
      +materialized: table
      +schema: intermediate
      +tags:
        - intermediate

    marts:
      +materialized: table
      +schema: marts
      +tags:
        - marts

seeds:
  adventureworks:
    +materialized: table
    +quote_columns: true
    +schema: raw_data
