adventureworks:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: desafioadventureworks-446600
      dataset: fact_dim
      threads: 4
      keyfile: /mnt/c/Temp/desafiolh-445818-3cb0f62cb9ef.json
