airflow dags delete conditional_dataset_and_time_based_timetable --yes
airflow dags delete consume_1_and_2_with_dataset_expressions --yes
airflow dags delete consume_1_or_2_with_dataset_expressions --yes
airflow dags delete consume_1_or_both_2_and_3_with_dataset_expressions --yes
airflow dags delete dataset_alias_example_alias_consumer --yes
airflow dags delete dataset_alias_example_alias_consumer_with_no_taskflow --yes
airflow dags delete dataset_alias_example_alias_producer --yes
airflow dags delete dataset_alias_example_alias_producer_with_no_taskflow --yes
airflow dags delete dataset_consumes_1 --yes
airflow dags delete dataset_consumes_1_and_2 --yes
airflow dags delete dataset_consumes_1_never_scheduled --yes
airflow dags delete dataset_consumes_unknown_never_scheduled --yes
airflow dags delete dataset_produces_1 --yes
airflow dags delete dataset_produces_2 --yes
airflow dags delete dataset_s3_bucket_consumer --yes
airflow dags delete dataset_s3_bucket_consumer_with_no_taskflow --yes
airflow dags delete dataset_s3_bucket_producer --yes
airflow dags delete dataset_s3_bucket_producer_with_no_taskflow --yes
airflow dags delete dataset_with_extra_by_context --yes
airflow dags delete dataset_with_extra_by_yield --yes
airflow dags delete dataset_with_extra_from_classic_operator --yes
airflow dags delete example_bash_decorator --yes
airflow dags delete example_bash_operator --yes
airflow dags delete example_branch_datetime_operator --yes
airflow dags delete example_branch_datetime_operator_2 --yes
airflow dags delete example_branch_datetime_operator_3 --yes
airflow dags delete example_branch_dop_operator_v3 --yes
airflow dags delete example_branch_labels --yes
airflow dags delete example_branch_operator --yes
airflow dags delete example_branch_python_operator_decorator --yes
airflow dags delete example_complex --yes
airflow dags delete example_dag_decorator --yes
airflow dags delete example_display_name --yes
airflow dags delete example_dynamic_task_mapping --yes
airflow dags delete example_dynamic_task_mapping_with_no_taskflow_operators --yes
airflow dags delete example_external_task_marker_child --yes
airflow dags delete example_external_task_marker_parent --yes
airflow dags delete example_nested_branch_dag --yes
airflow dags delete example_params_trigger_ui --yes
airflow dags delete example_params_ui_tutorial --yes
airflow dags delete example_passing_params_via_test_command --yes
airflow dags delete example_python_decorator --yes
airflow dags delete example_python_operator --yes
airflow dags delete example_sensor_decorator --yes
airflow dags delete example_sensors --yes
airflow dags delete example_setup_teardown --yes
airflow dags delete example_setup_teardown_taskflow --yes
airflow dags delete example_short_circuit_decorator --yes
airflow dags delete example_short_circuit_operator --yes
airflow dags delete example_skip_dag --yes
airflow dags delete example_sla_dag --yes
airflow dags delete example_subdag_operator --yes
airflow dags delete example_subdag_operator.section-1 --yes
airflow dags delete example_subdag_operator.section-2 --yes
airflow dags delete example_task_group --yes
airflow dags delete example_task_group_decorator --yes
airflow dags delete example_time_delta_sensor_async --yes
airflow dags delete example_trigger_controller_dag --yes
airflow dags delete example_trigger_target_dag --yes
airflow dags delete example_weekday_branch_operator --yes
airflow dags delete example_workday_timetable --yes
airflow dags delete example_xcom --yes
airflow dags delete example_xcom_args --yes
airflow dags delete example_xcom_args_with_operators --yes
airflow dags delete latest_only --yes
airflow dags delete latest_only_with_trigger --yes
airflow dags delete read_dataset_event --yes
airflow dags delete read_dataset_event_from_classic --yes
airflow dags delete tutorial --yes
airflow dags delete tutorial_dag --yes
airflow dags delete tutorial_objectstorage --yes
airflow dags delete tutorial_taskflow_api --yes
airflow dags delete tutorial_taskflow_api_virtualenv --yes
airflow dags delete tutorial_taskflow_templates --yes
