adventureworks:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: "C:/Temp/desafiolh-445818-3cb0f62cb9ef.json"
      project: "desafioadventureworks-445317"
      dataset: "stg_data"
      threads: 16

    staging:
      type: bigquery
      method: service-account
      keyfile: "C:/Temp/desafiolh-445818-3cb0f62cb9ef.json"
      project: "desafioadventureworks-445317"
      dataset: "stg_data"
      threads: 16

    marts:
      type: bigquery
      method: service-account
      keyfile: "C:/Temp/desafiolh-445818-3cb0f62cb9ef.json"
      project: "desafioadventureworks-445317"
      dataset: "marts_data"
      threads: 16
