version: 2

sources:
  - name: raw_data
    schema: raw_data
    tables:
      - name: humanresources_employee
        columns:
          - name: businessentityid
            data_type: int64
          - name: nationalidnumber
            data_type: string
          - name: loginid
            data_type: string
          - name: jobtitle
            data_type: string
          - name: birthdate
            data_type: date
          - name: maritalstatus
            data_type: string
          - name: gender
            data_type: string
          - name: hiredate
            data_type: date
          - name: salariedflag
            data_type: string
          - name: vacationhours
            data_type: int64
          - name: sickleavehours
            data_type: int64
          - name: currentflag
            data_type: string
          - name: rowguid
            data_type: string
          - name: modifieddate
            data_type: timestamp
          - name: organizationnode
            data_type: string

      - name: person_businessentity
        columns:
          - name: businessentityid
            data_type: int64
          - name: rowguid
            data_type: string
          - name: modifieddate
            data_type: timestamp

      - name: production_location
        columns:
          - name: locationid
            data_type: int64
          - name: name
            data_type: string
          - name: costrate
            data_type: numeric
          - name: availability
            data_type: numeric
          - name: modifieddate
            data_type: timestamp

      - name: production_productinventory
        columns:
          - name: productid
            data_type: int64
          - name: locationid
            data_type: int64
          - name: shelf
            data_type: string
          - name: bin
            data_type: int64
          - name: quantity
            data_type: int64
          - name: rowguid
            data_type: string
          - name: modifieddate
            data_type: timestamp

      - name: production_product
        columns:
          - name: productid
            data_type: int64
          - name: name
            data_type: string
          - name: productnumber
            data_type: string
          - name: makeflag
            data_type: string
          - name: finishedgoodsflag
            data_type: string
          - name: color
            data_type: string
          - name: safetystocklevel
            data_type: int64
          - name: reorderpoint
            data_type: int64
          - name: standardcost
            data_type: numeric
          - name: listprice
            data_type: numeric
          - name: size
            data_type: string
          - name: sizeunitmeasurecode
            data_type: string
          - name: weightunitmeasurecode
            data_type: string
          - name: weight
            data_type: numeric
          - name: daystomanufacture
            data_type: string
          - name: productline
            data_type: string
          - name: class
            data_type: string
          - name: style
            data_type: string
          - name: productsubcategoryid
            data_type: int64
          - name: productmodelid
            data_type: int64
          - name: sellstartdate
            data_type: timestamp
          - name: sellenddate
            data_type: timestamp
          - name: discontinueddate
            data_type: timestamp
          - name: rowguid
            data_type: string
          - name: modifieddate
            data_type: timestamp

      - name: sales_salesorderdetail
        columns:
          - name: salesorderid
            data_type: int64
          - name: salesorderdetailid
            data_type: int64
          - name: carriertrackingnumber
            data_type: string
          - name: orderqty
            data_type: int64
          - name: productid
            data_type: int64
          - name: specialofferid
            data_type: int64
          - name: unitprice
            data_type: numeric
          - name: unitpricediscount
            data_type: numeric
          - name: rowguid
            data_type: string
          - name: modifieddate
            data_type: timestamp

      - name: sales_salesorderheader
        columns:
          - name: salesorderid
            data_type: int64
          - name: revisionnumber
            data_type: int64
          - name: orderdate
            data_type: timestamp
          - name: duedate
            data_type: timestamp
          - name: shipdate
            data_type: timestamp
          - name: status
            data_type: int64
          - name: onlineorderflag
            data_type: string
          - name: purchaseordernumber
            data_type: string
          - name: accountnumber
            data_type: string
          - name: customerid
            data_type: int64
          - name: salespersonid
            data_type: int64
          - name: territoryid
            data_type: int64
          - name: billtoaddressid
            data_type: int64
          - name: shiptoaddressid
            data_type: int64
          - name: shipmethodid
            data_type: int64
          - name: creditcardid
            data_type: int64
          - name: creditcardapprovalcode
            data_type: string
          - name: currencyrateid
            data_type: int64
          - name: subtotal
            data_type: numeric
          - name: taxamt
            data_type: numeric
          - name: freight
            data_type: numeric
          - name: totaldue
            data_type: numeric
          - name: comment
            data_type: string
          - name: rowguid
            data_type: string
          - name: modifieddate
            data_type: timestamp

      - name: sales_store
        columns:
          - name: businessentityid
            data_type: int64
          - name: name
            data_type: string
          - name: salespersonid
            data_type: int64
          - name: demographics
            data_type: string
          - name: rowguid
            data_type: string
          - name: modifieddate
            data_type: timestamp
            
      - name: person_person
        columns:
          - name: businessentityid
            data_type: int64
          - name: firstname
            data_type: string
          - name: middlename
            data_type: string
          - name: lastname
            data_type: string
          - name: rowguid
            data_type: string
          - name: modifieddate
            data_type: timestamp

      - name: sales_customer
        columns:
          - name: customerid
            data_type: int64
          - name: personid
            data_type: int64
          - name: storeid
            data_type: int64
          - name: territoryid
            data_type: int64
          - name: rowguid
            data_type: string
          - name: modifieddate
            data_type: 
            
      - name: production_productsubcategory
        columns:
          - name: productsubcategoryid
            data_type: int64
          - name: name
            data_type: string
          - name: rowguid
            data_type: string
          - name: modifieddate
            data_type: timestamp


      - name: sales_salesterritory
        columns:
          - name: territoryid
            data_type: int64
          - name: name
            data_type: string
          - name: countryregioncode
            data_type: string
          - name: group
            data_type: string
          - name: rowguid
            data_type: string
          - name: modifieddate
            data_type: timestamp

      - name: production_productcategory
        columns:
          - name: productcategoryid
            data_type: int64
          - name: name
            data_type: string
          - name: rowguid
            data_type: string
          - name: modifieddate
            data_type: timestamp

      - name: person_address
        columns:
          - name: addressid
            data_type: int64
          - name: addressline1
            data_type: string
          - name: addressline2
            data_type: string
          - name: city
            data_type: string
          - name: stateprovinceid
            data_type: int64
          - name: postalcode
            data_type: string
          - name: rowguid
            data_type: string
          - name: modifieddate
            data_type: timestamp








