-- {{ config(materialized='table') }}

-- -- with 
-- --     product as (
-- --         select
-- --             productid_id
-- --             ,name_nm as product_name
-- --             ,productnumber_cd as product_number
-- --             ,standardcost_vr
-- --             ,listprice_vr
-- --             ,modifieddate_ts as product_modifieddate
-- --         from {{ ref('stg_production_product') }}
-- --     )
-- --     ,product_inventory as (
-- --         select
-- --             productid_id
-- --             ,locationid_id
-- --             ,shelf_desc
-- --             ,bin_desc
-- --             ,quantity_qt
-- --             ,modifieddate_ts as inventory_modifieddate
-- --         from {{ ref('stg_production_inventory') }}
-- --     )
-- --     ,joined_data as (
-- --         select
-- --             product.productid_id
-- --             ,product.product_name
-- --             ,product.product_number
-- --             ,product_inventory.locationid_id
-- --             ,product_inventory.shelf_desc
-- --             ,product_inventory.bin_desc
-- --             ,product_inventory.quantity_qt
-- --             ,greatest(product.product_modifieddate, product_inventory.inventory_modifieddate) as last_modifieddate
-- --         from product
-- --         join product_inventory
-- --             on product.productid_id = product_inventory.productid_id
-- --     )
-- -- select
-- --     joined_data.productid_id
-- --     ,joined_data.product_name
-- --     ,joined_data.product_number
-- --     ,joined_data.locationid_id
-- --     ,joined_data.shelf_desc
-- --     ,joined_data.bin_desc
-- --     ,sum(joined_data.quantity_qt) as total_quantity
-- --     ,max(joined_data.last_modifieddate) as last_inventory_update
-- -- from joined_data
-- -- group by
-- --     joined_data.productid_id
-- --     ,joined_data.product_name
-- --     ,joined_data.product_number
-- --     ,joined_data.locationid_id
-- --     ,joined_data.shelf_desc
-- --     ,joined_data.bin_desc
